# Generated by Django 2.0.7 on 2018-07-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True, verbose_name='Código de Acesso')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('apelido', models.CharField(max_length=150, verbose_name='Apelido')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=20, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, unique=True, verbose_name='RG')),
                ('cnpj', models.CharField(max_length=40, unique=True, verbose_name='CNPJ')),
                ('ie', models.CharField(max_length=20, verbose_name='IE')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
                ('site', models.CharField(max_length=50, verbose_name='Site')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=6, verbose_name='Nº')),
                ('complemento', models.CharField(max_length=40, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=40, verbose_name='Bairro')),
                ('cep', models.CharField(max_length=40, verbose_name='CEP')),
                ('cidade', models.CharField(max_length=40, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=40, verbose_name='Estado')),
            ],
        ),
    ]
