# Generated by Django 2.0.7 on 2018-08-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Saldo Caixa'),
        ),
    ]
