# Generated by Django 2.0.7 on 2018-08-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0003_auto_20180807_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Caixa'),
        ),
    ]
