# Generated by Django 2.0.7 on 2018-08-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0004_auto_20180807_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='data_da_compra',
            new_name='data_da_entrada',
        ),
    ]
